# Generated by Django 3.0.8 on 2020-07-14 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OddamWDobreRece', '0003_auto_20200714_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
