# Generated by Django 3.0.8 on 2020-07-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OddamWDobreRece', '0004_auto_20200714_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='year_in_school',
            new_name='type',
        ),
    ]
