# Generated by Django 3.0.8 on 2020-07-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OddamWDobreRece', '0005_auto_20200714_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
