# Generated by Django 3.0.8 on 2020-07-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OddamWDobreRece', '0007_auto_20200717_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(null=True),
        ),
    ]
